SET BASEDIR=%~dp0

SET MIGRATION_PROJECT=%BASEDIR%\\PostgreSqlMigration\\PostgreSqlMigration.csproj
SET MAIN_PROJECT=%BASEDIR%\\..\\src\\ServiceName\\ServiceName.csproj

SET SMUSDI_APPSETTINGS_FOLDER=%BASEDIR%\\..\\{APPSETTINGS_FOLDER_PATH}{APPSETTINGS_FOLDER_NAME}
SET SMUSDI_SERVICE_NAME=serviceKebabCase
SET ASPNETCORE_ENVIRONMENT=Development
SET POSTGRES_HOST=localhost
SET POSTGRES_DB=smusdi
SET POSTGRES_USER=smusdi
SET POSTGRES_PASSWORD=smusdi
SET POSTGRES_PORT=5432
SET MIGRATE_DATABASE=false
