name: Publish packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Pack
        run: dotnet pack Smusdi.Templates.csproj -p:PackageVersion=${{ github.event.release.tag_name }} -o publish
      - name: Publish
        run: dotnet nuget push publish/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "https://nuget.pkg.github.com/LionMarc/index.json"
      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: publish/*.nupkg
